### ISSUE TITLE
Hot-reload a node.js process running in a Container on Vagrant, OS X

### ISSUE THREAD

**Issue by christophercliff** [docker-library/node#31]
I'm trying to find a development workflow for OS X/Vagrant/Docker/node.js. If I were developing on OS X, I would use something like [node-supervisor](https://github.com/isaacs/node-supervisor) to restart the process during development. When I run the same server in in a Docker Container, supervisor doesn't restart the process.

Is it possible to run a node.js Container on OS X with hot-reload?

**Comment by brainsiq** [comment]
I've been using forever js inside the container to auto-reload when files change.

**Comment by christophercliff** [comment]
@brainsiq Mind sharing your Vagrant and Docker configuration?

**Comment by brainsiq** [comment]
I've not used node-supervisor before but it looks like it'd be setup very similarly. Maybe it just works differently and that's why it's not working for you...

Not using Vagrant at all but have a Dockerfile like this:

```
FROM node:0.10.35

RUN npm install -g forever

# add only package.json so docker uses the cache to build image except when a dependency has changed
ADD package.json /src/package.json

RUN cd src && npm install

# add remaining source code to container so we can actually run the app
ADD . /src

WORKDIR /src

EXPOSE 8080

CMD npm start
```

Then the application's package.json file defines the start command:

```
{
  "name": "my app",
  "version": "1.0.0",
  "scripts": {
    "start": "forever -a -w -l forever.log -o logs/stdout.log -e logs/stderr.log app.js"
   }
}
```

So now we can build our image from the application root directory:

```
docker build --rm -t myapp .
```

So then we have 2 ways of running this. 

1. Run using the source code that was added to the image at the time of building the image. This is what we use to continuously deploy the app:

```
docker run -P --name myappcontainer myapp
```

2. Re-mount the source code from the host container so we can edit files in sublime text/atom/another editor on the host and have the app automatically restart using forever. We have to open a bash prompt in the container first and run npm install as mounting the source code again wipes out the container's node_modules folder, but this only has to be done once when the container is first created.

```
docker run -it -P -v $(pwd):/src --name myappcontainer myapp bash

# inside the container
> npm install
> npm start
```

It might not be the best or most efficient way but it seems to work fairly well for our purposes.

**Comment by christophercliff** [comment]
It's my understanding that the only way to run Docker on OS X is through a VM using Vagrant (or similar). Is that not the case?

**Comment by brainsiq** [comment]
Can't really help you with that bit I'm afraid as I'm running on Ubuntu but looks like the official installation docs say to use boot2docker for OS X.

The details I gave above will work on any host environment as all the magic happens inside the container. So once you have docker running on OS X it should work okay.

**Comment by christophercliff** [comment]
boot2docker just creates a VM with VirtualBox. And the Vagrant provider [does use boot2docker](https://docs.vagrantup.com/v2/docker/basics.html).

I think the ideal workflow would be syncing the source files from OS X to the VM (Vagrant does this), *then* syncing from the VM host to the Docker container (Docker does this), *then* automatically restarting the node.js process.

It's the automatic reload that's causing a problem. And it can take upwards of 10s for changes to reach the container. This may not be a viable workflow, but I know lots of node.js developers run on OS X so I thought somebody might have come up with a solution.

**Comment by yosifkit** [comment]
Closing old issue, (should be reported on the new repo https://github.com/nodejs/docker-node if you still have issues).
